article:
  aerzteblatt: previous
  berliner-zeitung: lastdot
  dieostschweiz: last
  epochtimes: last
  nordkurier: last
  linth24: first
  nachdenkseiten: page
  n-tv: last
  rnd: last
  rt: first
  welt: previous
sitename:
  achgut: Achgut.com
  dieostschweiz: Die Ostschweiz
  epochtimes: Epoch Times
  heise: Telepolis
  infosperber: INFOsperber
  insideparadeplatz: In$ide Paradeplatz
  medinside: medinside.ch
  multipolar-magazin: multipolar
  nachdenkseiten: NachDenkSeiten
  nordkurier: Nordkurier
  n-tv: ntv
  reitschuster: reitschuster
  rubikon: Rubikon
  srf: SRF
  substack: substack.com
  swr: SWR
  tkp: tp - Science & Technology
  uncutnews: Uncut-News
  unser-mitteleuropa: Unser Mitteleuropa
  welt: Die Welt
  zueriost: züriost
tag:
  achgut: achgut
  2020news: 2020news
  aerzteblatt: ärzteblatt
  corona-blog: corona-blog
  insideparadeplatz: inside-paradeplatz
  medinside: medinside
  rt: rt
  substack: substack
  tichyseinblick: tichyseinblick
  tkp: tkp
  welt: welt
subtitle:
  corona-blog: last
  corona-transition: last
  insideparadeplatz: last
  infosperber: last
  nordkurier: last
  reitschuster: last
  uncutnews: last
  unser-mitteleuropa: ignore-og
  welt: last
  weltwoche-daily: last
