article:
  aerzteblatt: previous
  aerztezeitung: last
  admin: last
  ardmediathek: pprevious
  berliner-zeitung: lastdot
  bernerzeitung: last
  comm4u: page
  deutschlandfunk: page
  derstandard: previous
  dieostschweiz: last
  epochtimes: last
  focus: last_
  fm1today: last
  heise: last
  meinbezirk: last_
  nordkurier: last
  linth24: first
  nachdenkseiten: page
  nau: last
  ndr: lastcomma
  n-tv: last
  nzz: lastdot
  pharmazeutische-zeitung: last
  rnd: last
  rt: first
  snanews: last
  tagesanzeiger: last
  tagblatt: lastdot
  unilu: last
  unzensuriert: first
  welt: previous
sitename:
  2020news: 2020 News
  achgut: Achgut.com
  admin: Bundesrat
  aerztezeitung: AerzteZeitung
  ardmediathek: ARD
  deutsche-apotheker-zeitung: Deutsche Apotheker Zeitung
  derstandard: Der Standard
  dieostschweiz: Die Ostschweiz
  epochtimes: Epoch Times
  fm1today: FM1 Today
  focus: Focus Online
  gesundheitstipp: Gesundheitstipp
  heise: Telepolis
  infosperber: INFOsperber
  insideparadeplatz: In$ide Paradeplatz
  kenfm: kenFM
  kinder-maskenpetition: Kinder-Maskenpetition
  ktipp: Ktipp
  medinside: medinside.ch
  multipolar-magazin: multipolar
  nachdenkseiten: NachDenkSeiten
  nordkurier: Nordkurier
  ndr: NDR
  n-tv: ntv
  nzz: NZZ
  pharmazeutische-zeitung: Pharmazeutische Zeitung
  reitschuster: reitschuster
  rnd: RND
  rubikon: Rubikon
  srf: SRF
  substack: substack.com
  swissmedic: Swissmedic
  swr: SWR
  tagesanzeiger: Tagesanzeiger
  tagblatt: tagblatt.ch
  tkp: tp - Science & Technology
  uncutnews: Uncut-News
  unser-mitteleuropa: Unser Mitteleuropa
  welt: Die Welt
  weltwoche: Weltwoche
  zdf: ZDF
  zeitpunkt: ZE!TPUNKT
  zueriost: züriost
tag:
  2020news: 2020news
  aargau-zuerich: aargau-zuerich
  achgut: achgut
  admin: bundesrat
  aerzteblatt: ärzteblatt
  bernerzeitung: bernerzeitung
  corona-blog: corona-blog
  deutsche-apotheker-zeitung: daz
  dgkj: dgkj
  ema: ema
  fm1today: fm1today
  focus: focus
  infekt: infekt
  insideparadeplatz: inside-paradeplatz
  medinside: medinside
  meinbezirk: meinbezirk
  rt: rt
  substack: substack
  derstandard: standard
  schweizermonat: schweizermonat
  svp: svp
  swprs: swprs
  tagblatt: tagblatt
  tichyseinblick: tichyseinblick
  tkp: tkp
  vera-lengsfeld: vera-lengsfeld
  harald-walach: walach
  welt: welt
  zeitpunkt: zeitpunkt
subtitle:
  2020news: last-
  corona-blog: last2-
  corona-transition: last
  harald-walach: last-
  insideparadeplatz: last-
  infekt: last-
  infosperber: last-
  journalistenwatch: last›
  kenfm: last
  ktipp: last2-
  medinside: ignore-og
  nordkurier: last
  nzz: last
  pharmazeutische-zeitung: last
  pubmed: last-
  reitschuster: last-
  schweizermonat: last–
  tagblatt: last
  tkp: last-
  uncutnews: last
  unser-mitteleuropa: last
  unzensuriert: last-
  verfassungsfreunde: last
  welt: last-
  weltwoche-daily: last-
  zeitpunkt: h2
uri:
  fassadenkratzer.wordpress.com: first
  pubmed.ncbi.nlm.nih.gov: first
  www.ema.europa.eu: second
cleanurl:
  nachdenkseiten: false
  deutschlandfunk: false
country:
  achgut: DE
  corona-blog: DE
  corona-transition: CH
  fassadenkratzer: DE
  rt: DE
  rubikon: DE
  sciencefiles: DE
  unser-mitteleuropa: EU
