article:
  aerzteblatt: previous
  aerztezeitung: last
  berliner-zeitung: lastdot
  deutschlandfunk: page
  dieostschweiz: last
  epochtimes: last
  focus: last_
  fm1today: last
  nordkurier: last
  linth24: first
  nachdenkseiten: page
  ndr: lastcomma
  n-tv: last
  nzz: lastdot
  rnd: last
  rt: first
  tagesanzeiger: last
  welt: previous
sitename:
  2020news: 2020 News
  achgut: Achgut.com
  aerztezeitung: AerzteZeitung
  deutsche-apotheker-zeitung: Deutsche Apotheker Zeitung
  dieostschweiz: Die Ostschweiz
  epochtimes: Epoch Times
  fm1today: FM1 Today
  focus: Focus Online
  heise: Telepolis
  infosperber: INFOsperber
  insideparadeplatz: In$ide Paradeplatz
  kenfm: kenFM
  kinder-maskenpetition: Kinder-Maskenpetition
  ktipp: Ktipp
  medinside: medinside.ch
  multipolar-magazin: multipolar
  nachdenkseiten: NachDenkSeiten
  nordkurier: Nordkurier
  n-tv: ntv
  ndr: NDR
  nzz: NZZ
  pharmazeutische-zeitung: Pharmazeutische Zeitung
  reitschuster: reitschuster
  rnd: RND
  rubikon: Rubikon
  srf: SRF
  substack: substack.com
  swissmedic: Swissmedic
  swr: SWR
  tagesanzeiger: Tagesanzeiger
  tkp: tp - Science & Technology
  uncutnews: Uncut-News
  unser-mitteleuropa: Unser Mitteleuropa
  welt: Die Welt
  weltwoche: Weltwoche
  zdf: ZDF
  zeitpunkt: ZE!TPUNKT
  zueriost: züriost
tag:
  2020news: 2020news
  aargau-zuerich: aargau-zuerich
  achgut: achgut
  aerzteblatt: ärzteblatt
  corona-blog: corona-blog
  deutsche-apotheker-zeitung: daz
  fm1today: fm1today
  focus: focus
  insideparadeplatz: inside-paradeplatz
  medinside: medinside
  rt: rt
  substack: substack
  tichyseinblick: tichyseinblick
  tkp: tkp
  welt: welt
subtitle:
  2020news: last
  corona-blog: last
  corona-transition: last
  insideparadeplatz: last
  infekt: last
  infosperber: last
  kenfm: last
  medinside: ignore-og
  nordkurier: last
  reitschuster: last
  uncutnews: last
  unser-mitteleuropa: ignore-og
  welt: last
  verfassungsfreunde: last
  weltwoche-daily: last
cleanurl:
  nachdenkseiten: false
  deutschlandfunk: false
country:
  rt: DE
