- name: Keep Remote File Locally Up-to-date
  # You may pin to the exact commit or the version.
  # uses: TheLastProject/keep-remote-file-locally-up-to-date-action@8fb9abb447d2ea6ec8dd40c94879eb193fd6ffa0
  uses: TheLastProject/keep-remote-file-locally-up-to-date-action@v1
  with:
    # The url of the file to download
    url: https://demo.terminkalender.top/demotermine.csv
    # The location of the file in the repository to update if changed
    file_in_repo: _data/demotermine.csv
    # The name of the git user
    git_user: # default is thelastproject/keep-remote-locally-up-to-date
    # The email of the git user
    git_email: # default is no-reply@github.com
